# Generated by Django 4.2.3 on 2023-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
